function(init_freeimage)

    set(FREEIMAGE_DIR "${CMAKE_SOURCE_DIR}/external/freeimage")

    set(FREEIMAGE_SRC
        ${FREEIMAGE_DIR}/FreeImage/BitmapAccess.cpp
        ${FREEIMAGE_DIR}/FreeImage/ColorLookup.cpp
        ${FREEIMAGE_DIR}/FreeImage/FreeImage.cpp
        ${FREEIMAGE_DIR}/FreeImage/FreeImageC.c
        ${FREEIMAGE_DIR}/FreeImage/FreeImageIO.cpp
        ${FREEIMAGE_DIR}/FreeImage/GetType.cpp
        ${FREEIMAGE_DIR}/FreeImage/MemoryIO.cpp
        ${FREEIMAGE_DIR}/FreeImage/PixelAccess.cpp
        ${FREEIMAGE_DIR}/FreeImage/J2KHelper.cpp
        ${FREEIMAGE_DIR}/FreeImage/MNGHelper.cpp
        ${FREEIMAGE_DIR}/FreeImage/Plugin.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginBMP.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginCUT.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginDDS.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginEXR.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginGIF.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginHDR.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginICO.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginIFF.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginJ2K.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginJNG.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginJP2.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginJPEG.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginKOALA.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginMNG.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPCD.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPCX.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPFM.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPICT.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPNG.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPNM.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginPSD.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginRAS.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginRAW.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginSGI.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginTARGA.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginWBMP.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginXBM.cpp
        ${FREEIMAGE_DIR}/FreeImage/PluginXPM.cpp
        ${FREEIMAGE_DIR}/FreeImage/PSDParser.cpp
        ${FREEIMAGE_DIR}/FreeImage/TIFFLogLuv.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion16_555.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion16_565.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion24.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion32.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion4.cpp
        ${FREEIMAGE_DIR}/FreeImage/Conversion8.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionFloat.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionRGB16.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionRGBA16.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionRGBAF.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionRGBF.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionType.cpp
        ${FREEIMAGE_DIR}/FreeImage/ConversionUINT16.cpp
        ${FREEIMAGE_DIR}/FreeImage/Halftoning.cpp
        ${FREEIMAGE_DIR}/FreeImage/tmoColorConvert.cpp
        ${FREEIMAGE_DIR}/FreeImage/tmoDrago03.cpp
        ${FREEIMAGE_DIR}/FreeImage/tmoFattal02.cpp
        ${FREEIMAGE_DIR}/FreeImage/tmoReinhard05.cpp
        ${FREEIMAGE_DIR}/FreeImage/ToneMapping.cpp
        ${FREEIMAGE_DIR}/FreeImage/LFPQuantizer.cpp
        ${FREEIMAGE_DIR}/FreeImage/NNQuantizer.cpp
        ${FREEIMAGE_DIR}/FreeImage/WuQuantizer.cpp
        ${FREEIMAGE_DIR}/FreeImage/CacheFile.cpp
        ${FREEIMAGE_DIR}/FreeImage/MultiPage.cpp
        ${FREEIMAGE_DIR}/FreeImage/ZLibInterface.cpp
        ${FREEIMAGE_DIR}/Metadata/Exif.cpp
        ${FREEIMAGE_DIR}/Metadata/FIRational.cpp
        ${FREEIMAGE_DIR}/Metadata/FreeImageTag.cpp
        ${FREEIMAGE_DIR}/Metadata/IPTC.cpp
        ${FREEIMAGE_DIR}/Metadata/TagConversion.cpp
        ${FREEIMAGE_DIR}/Metadata/TagLib.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Background.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/BSplineRotate.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Channels.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/ClassicRotate.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Colors.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/CopyPaste.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Display.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Flip.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/JPEGTransform.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/MultigridPoissonSolver.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Rescale.cpp
        ${FREEIMAGE_DIR}/FreeImageToolkit/Resize.cpp
        ${FREEIMAGE_DIR}/LibJPEG/./jaricom.c
        ${FREEIMAGE_DIR}/LibJPEG/jcapimin.c
        ${FREEIMAGE_DIR}/LibJPEG/jcapistd.c
        ${FREEIMAGE_DIR}/LibJPEG/./jcarith.c
        ${FREEIMAGE_DIR}/LibJPEG/jccoefct.c
        ${FREEIMAGE_DIR}/LibJPEG/jccolor.c
        ${FREEIMAGE_DIR}/LibJPEG/jcdctmgr.c
        ${FREEIMAGE_DIR}/LibJPEG/jchuff.c
        ${FREEIMAGE_DIR}/LibJPEG/jcinit.c
        ${FREEIMAGE_DIR}/LibJPEG/jcmainct.c
        ${FREEIMAGE_DIR}/LibJPEG/jcmarker.c
        ${FREEIMAGE_DIR}/LibJPEG/jcmaster.c
        ${FREEIMAGE_DIR}/LibJPEG/jcomapi.c
        ${FREEIMAGE_DIR}/LibJPEG/jcparam.c
        ${FREEIMAGE_DIR}/LibJPEG/jcprepct.c
        ${FREEIMAGE_DIR}/LibJPEG/jcsample.c
        ${FREEIMAGE_DIR}/LibJPEG/jctrans.c
        ${FREEIMAGE_DIR}/LibJPEG/jdapimin.c
        ${FREEIMAGE_DIR}/LibJPEG/jdapistd.c
        ${FREEIMAGE_DIR}/LibJPEG/./jdarith.c
        ${FREEIMAGE_DIR}/LibJPEG/jdatadst.c
        ${FREEIMAGE_DIR}/LibJPEG/jdatasrc.c
        ${FREEIMAGE_DIR}/LibJPEG/jdcoefct.c
        ${FREEIMAGE_DIR}/LibJPEG/jdcolor.c
        ${FREEIMAGE_DIR}/LibJPEG/jddctmgr.c
        ${FREEIMAGE_DIR}/LibJPEG/jdhuff.c
        ${FREEIMAGE_DIR}/LibJPEG/jdinput.c
        ${FREEIMAGE_DIR}/LibJPEG/jdmainct.c
        ${FREEIMAGE_DIR}/LibJPEG/jdmarker.c
        ${FREEIMAGE_DIR}/LibJPEG/jdmaster.c
        ${FREEIMAGE_DIR}/LibJPEG/jdmerge.c
        ${FREEIMAGE_DIR}/LibJPEG/jdpostct.c
        ${FREEIMAGE_DIR}/LibJPEG/jdsample.c
        ${FREEIMAGE_DIR}/LibJPEG/jdtrans.c
        ${FREEIMAGE_DIR}/LibJPEG/jerror.c
        ${FREEIMAGE_DIR}/LibJPEG/jfdctflt.c
        ${FREEIMAGE_DIR}/LibJPEG/jfdctfst.c
        ${FREEIMAGE_DIR}/LibJPEG/jfdctint.c
        ${FREEIMAGE_DIR}/LibJPEG/jidctflt.c
        ${FREEIMAGE_DIR}/LibJPEG/jidctfst.c
        ${FREEIMAGE_DIR}/LibJPEG/jidctint.c
        ${FREEIMAGE_DIR}/LibJPEG/jmemmgr.c
        ${FREEIMAGE_DIR}/LibJPEG/jmemnobs.c
        ${FREEIMAGE_DIR}/LibJPEG/jquant1.c
        ${FREEIMAGE_DIR}/LibJPEG/jquant2.c
        ${FREEIMAGE_DIR}/LibJPEG/jutils.c
        ${FREEIMAGE_DIR}/LibJPEG/transupp.c
        ${FREEIMAGE_DIR}/LibPNG/./png.c
        ${FREEIMAGE_DIR}/LibPNG/./pngerror.c
        ${FREEIMAGE_DIR}/LibPNG/./pngget.c
        ${FREEIMAGE_DIR}/LibPNG/./pngmem.c
        ${FREEIMAGE_DIR}/LibPNG/./pngpread.c
        ${FREEIMAGE_DIR}/LibPNG/./pngread.c
        ${FREEIMAGE_DIR}/LibPNG/./pngrio.c
        ${FREEIMAGE_DIR}/LibPNG/./pngrtran.c
        ${FREEIMAGE_DIR}/LibPNG/./pngrutil.c
        ${FREEIMAGE_DIR}/LibPNG/./pngset.c
        ${FREEIMAGE_DIR}/LibPNG/./pngtrans.c
        ${FREEIMAGE_DIR}/LibPNG/./pngwio.c
        ${FREEIMAGE_DIR}/LibPNG/./pngwrite.c
        ${FREEIMAGE_DIR}/LibPNG/./pngwtran.c
        ${FREEIMAGE_DIR}/LibPNG/./pngwutil.c
        ${FREEIMAGE_DIR}/ZLib/./adler32.c
        ${FREEIMAGE_DIR}/ZLib/./compress.c
        ${FREEIMAGE_DIR}/ZLib/./crc32.c
        ${FREEIMAGE_DIR}/ZLib/./deflate.c
        ${FREEIMAGE_DIR}/ZLib/./gzclose.c
        ${FREEIMAGE_DIR}/ZLib/./gzlib.c
        ${FREEIMAGE_DIR}/ZLib/./gzread.c
        ${FREEIMAGE_DIR}/ZLib/./gzwrite.c
        ${FREEIMAGE_DIR}/ZLib/./infback.c
        ${FREEIMAGE_DIR}/ZLib/./inffast.c
        ${FREEIMAGE_DIR}/ZLib/./inflate.c
        ${FREEIMAGE_DIR}/ZLib/./inftrees.c
        ${FREEIMAGE_DIR}/ZLib/./trees.c
        ${FREEIMAGE_DIR}/ZLib/./uncompr.c
        ${FREEIMAGE_DIR}/ZLib/./zutil.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/bio.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/cio.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/dwt.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/event.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/./function_list.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/image.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/./invert.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/j2k.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/jp2.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/mct.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/mqc.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/openjpeg.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/./opj_clock.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/pi.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/raw.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/t1.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/t2.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/tcd.c
        ${FREEIMAGE_DIR}/LibOpenJPEG/tgt.c
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/b44ExpLogTable.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfAcesFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfB44Compressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfBoxAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfChannelList.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfChannelListAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfChromaticities.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfChromaticitiesAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfCompositeDeepScanLine.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfCompressionAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfCompressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfConvert.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfCRgbaFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepCompositing.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepFrameBuffer.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepImageStateAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepScanLineInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepScanLineInputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepScanLineOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepScanLineOutputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepTiledInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepTiledInputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepTiledOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDeepTiledOutputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDoubleAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfDwaCompressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfEnvmap.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfEnvmapAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfFastHuf.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfFloatAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfFloatVectorAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfFrameBuffer.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfFramesPerSecond.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfGenericInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfGenericOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfHeader.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfHuf.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfInputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfInputPartData.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfIntAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfIO.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfKeyCode.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfKeyCodeAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfLineOrderAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfLut.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfMatrixAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfMisc.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfMultiPartInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfMultiPartOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfMultiView.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfOpaqueAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfOutputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfOutputPartData.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfPartType.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfPizCompressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfPreviewImage.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfPreviewImageAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfPxr24Compressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRational.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRationalAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRgbaFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRgbaYca.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRle.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfRleCompressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfScanLineInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfStandardAttributes.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfStdIO.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfStringAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfStringVectorAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfSystemSpecific.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTestFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfThreading.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTileDescriptionAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledInputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledInputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledMisc.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledOutputFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledOutputPart.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTiledRgbaFile.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTileOffsets.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTimeCode.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfTimeCodeAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfVecAttribute.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfVersion.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfWav.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfZip.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmImf/ImfZipCompressor.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathBox.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathColorAlgo.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathFun.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathMatrixAlgo.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathRandom.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathShear.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Imath/ImathVec.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Iex/IexBaseExc.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Iex/IexThrowErrnoExc.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./Half/half.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmThread/IlmThread.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmThread/IlmThreadMutex.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmThread/IlmThreadPool.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IlmThread/IlmThreadSemaphore.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IexMath/IexMathFloatExc.cpp
        ${FREEIMAGE_DIR}/OpenEXR/./IexMath/IexMathFpu.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./internal/dcraw_common.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./internal/dcraw_fileio.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./internal/demosaic_packs.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./src/libraw_c_api.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./src/libraw_cxx.cpp
        ${FREEIMAGE_DIR}/LibRawLite/./src/libraw_datastream.cpp
        ${FREEIMAGE_DIR}/MapIntrospector.h
        ${FREEIMAGE_DIR}/FreeImage
        ${FREEIMAGE_DIR}/CacheFile.h
        ${FREEIMAGE_DIR}/LibJPEG/cderror.h
        ${FREEIMAGE_DIR}/LibJPEG/jmorecfg.h
        ${FREEIMAGE_DIR}/LibJPEG/transupp.h
        ${FREEIMAGE_DIR}/LibJPEG/jpeglib.h
        ${FREEIMAGE_DIR}/LibJPEG/jversion.h
        ${FREEIMAGE_DIR}/LibJPEG/jinclude.h
        ${FREEIMAGE_DIR}/LibJPEG/jerror.h
        ${FREEIMAGE_DIR}/LibJPEG/jconfig.h
        ${FREEIMAGE_DIR}/LibJPEG/jdct.h
        ${FREEIMAGE_DIR}/LibJPEG/cdjpeg.h
        ${FREEIMAGE_DIR}/LibJPEG/jmemsys.h
        ${FREEIMAGE_DIR}/LibJPEG/jpegint.h
        ${FREEIMAGE_DIR}/Plugin.h
        ${FREEIMAGE_DIR}/Metadata/FreeImageTag.h
        ${FREEIMAGE_DIR}/Metadata/FIRational.h
        ${FREEIMAGE_DIR}/ToneMapping.h
        ${FREEIMAGE_DIR}/FreeImageIO.h
        ${FREEIMAGE_DIR}/FreeImage.h
        ${FREEIMAGE_DIR}/FreeImage/PSDParser.h
        ${FREEIMAGE_DIR}/FreeImage/J2KHelper.h
        ${FREEIMAGE_DIR}/ZLib/trees.h
        ${FREEIMAGE_DIR}/ZLib/inffixed.h
        ${FREEIMAGE_DIR}/ZLib/inflate.h
        ${FREEIMAGE_DIR}/ZLib/zlib.h
        ${FREEIMAGE_DIR}/ZLib/zconf.h
        ${FREEIMAGE_DIR}/ZLib/inftrees.h
        ${FREEIMAGE_DIR}/ZLib/zutil.h
        ${FREEIMAGE_DIR}/ZLib/inffast.h
        ${FREEIMAGE_DIR}/ZLib/crc32.h
        ${FREEIMAGE_DIR}/ZLib/gzguts.h
        ${FREEIMAGE_DIR}/ZLib/deflate.h
        ${FREEIMAGE_DIR}/Quantizers.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/cio.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/mqc.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/cidx_manager.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/function_list.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/indexbox_manager.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_config.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_clock.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/event.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_codec.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/pi.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/dwt.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/tgt.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/invert.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_malloc.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/raw.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/jp2.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/bio.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/t2.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/mct.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/t1.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/t1_luts.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/j2k.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_stdint.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_config_private.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_includes.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_intmath.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/image.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/opj_inttypes.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/openjpeg.h
        ${FREEIMAGE_DIR}/LibOpenJPEG/tcd.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_version.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_const.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_types.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_alloc.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_datastream.h
        ${FREEIMAGE_DIR}/LibRawLite/libraw/libraw_internal.h
        ${FREEIMAGE_DIR}/LibRawLite/internal/var_defines.h
        ${FREEIMAGE_DIR}/LibRawLite/internal/defines.h
        ${FREEIMAGE_DIR}/LibRawLite/internal/libraw_internal_funcs.h
        ${FREEIMAGE_DIR}/LibPNG/png.h
        ${FREEIMAGE_DIR}/LibPNG/pngdebug.h
        ${FREEIMAGE_DIR}/LibPNG/pnginfo.h
        ${FREEIMAGE_DIR}/LibPNG/pnglibconf.h
        ${FREEIMAGE_DIR}/LibPNG/pngstruct.h
        ${FREEIMAGE_DIR}/LibPNG/pngpriv.h
        ${FREEIMAGE_DIR}/LibPNG/pngconf.h
        ${FREEIMAGE_DIR}/Utilities.h
        ${FREEIMAGE_DIR}/FreeImageToolkit/Resize.h
        ${FREEIMAGE_DIR}/FreeImageToolkit/Filters.h
        ${FREEIMAGE_DIR}/OpenEXR/OpenEXRConfig.h
        ${FREEIMAGE_DIR}/OpenEXR/IexMath/IexMathFloatExc.h
        ${FREEIMAGE_DIR}/OpenEXR/IexMath/IexMathFpu.h
        ${FREEIMAGE_DIR}/OpenEXR/IexMath/IexMathIeeeExc.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThread.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadMutex.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadForward.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadExport.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadSemaphore.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadPool.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmThread/IlmThreadNamespace.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexErrnoExc.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexMacros.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexForward.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexExport.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexThrowErrnoExc.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexNamespace.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexMathExc.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/IexBaseExc.h
        ${FREEIMAGE_DIR}/OpenEXR/Iex/Iex.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathColorAlgo.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathNamespace.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathVec.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathGL.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathSphere.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathEuler.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathLimits.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathQuat.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathRoots.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathFun.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathExport.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathShear.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathPlane.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathForward.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathHalfLimits.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathFrustumTest.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathMatrixAlgo.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathVecAlgo.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathInterval.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathBox.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathFrame.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathColor.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathMath.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathLine.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathBoxAlgo.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathFrustum.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathExc.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathLineAlgo.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathRandom.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathInt64.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathGLU.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathPlatform.h
        ${FREEIMAGE_DIR}/OpenEXR/Imath/ImathMatrix.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfIO.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfStdIO.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPreviewImage.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDwaCompressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfChannelList.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfInt64.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfGenericOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfHuf.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOptimizedPixelReading.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/b44ExpLogTable.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfMultiPartOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTileDescriptionAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfFastHuf.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/dwaLookups.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCompositeDeepScanLine.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepFrameBuffer.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfInputPartData.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfAcesFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRgbaYca.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfThreading.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfWav.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfChromaticitiesAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDwaCompressorSimd.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfNamespace.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfMatrixAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTimeCodeAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineInputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfFloatAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPxr24Compressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCompressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCRgbaFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledInputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRationalAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTileOffsets.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfInputStreamMutex.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfIntAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledOutputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPartType.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfStringAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepTiledOutputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRleCompressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfChromaticities.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTestFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfInputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfXdr.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOutputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfExport.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRgba.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfLineOrder.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCompression.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledMisc.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfFramesPerSecond.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfZipCompressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfKeyCodeAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfFloatVectorAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfMultiPartInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepTiledOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRational.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepImageStateAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfChannelListAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepCompositing.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOutputPartData.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepTiledInputPart.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPreviewImageAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfFrameBuffer.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepImageState.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOpaqueAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfEnvmapAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPizCompressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfStringVectorAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfMultiView.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfAutoArray.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfLut.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledOutputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfBoxAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCheckedArithmetic.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfB44Compressor.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfSystemSpecific.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRgbaFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTimeCode.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfVecAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDeepTiledInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfZip.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfConvert.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfMisc.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfHeader.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfForward.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPartHelper.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfKeyCode.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfVersion.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfStandardAttributes.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfPixelType.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfName.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfSimd.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfArray.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfOutputStreamMutex.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTiledRgbaFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfRle.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfScanLineInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfDoubleAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfGenericInputFile.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfEnvmap.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfLineOrderAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfTileDescription.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmImf/ImfCompressionAttribute.h
        ${FREEIMAGE_DIR}/OpenEXR/IlmBaseConfig.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/halfFunction.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/halfExport.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/half.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/eLut.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/halfLimits.h
        ${FREEIMAGE_DIR}/OpenEXR/Half/toFloat.h
    )

    add_library(FreeImage STATIC ${FREEIMAGE_SRC})
    set_target_properties(FreeImage PROPERTIES FOLDER "external")

    target_include_directories(FreeImage PUBLIC "${FREEIMAGE_DIR}")

    target_include_directories(FreeImage PRIVATE 
        "${FREEIMAGE_DIR}/Metadata"
        "${FREEIMAGE_DIR}/FreeImageToolkit"
        "${FREEIMAGE_DIR}/LibJPEG"
        "${FREEIMAGE_DIR}/LibPNG"
        "${FREEIMAGE_DIR}/ZLib"
        "${FREEIMAGE_DIR}/LibOpenJPEG"
        "${FREEIMAGE_DIR}/OpenEXR"
        "${FREEIMAGE_DIR}/OpenEXR/Half"
        "${FREEIMAGE_DIR}/OpenEXR/Iex"
        "${FREEIMAGE_DIR}/OpenEXR/IlmImf"
        "${FREEIMAGE_DIR}/OpenEXR/IlmThread"
        "${FREEIMAGE_DIR}/OpenEXR/Iexmath"
        "${FREEIMAGE_DIR}/OpenEXR/Imath"
        "${FREEIMAGE_DIR}/LibRawLite"
        "${FREEIMAGE_DIR}/LibRawLite/dcraw"
        "${FREEIMAGE_DIR}/LibRawLite/internal"
        "${FREEIMAGE_DIR}/LibRawLite/libraw"
        "${FREEIMAGE_DIR}/LibRawLite/src"
    )

    set_target_properties(FreeImage PROPERTIES CXX_STANDARD 11)

    add_definitions(-DOPJ_STATIC -DLIBRAW_NODLL -DFREEIMAGE_LIB)

    if (WIN32)
        target_compile_options(FreeImage PRIVATE /EHsc /W3 /wd4305 /wd4267 /wd4244 /wd4334 /wd4018 /wd4311 /wd4302 /wd4297 /wd4996 /wd4804 /wd4101 /wd4146 /wd4806)
        target_compile_definitions(FreeImage PRIVATE -DWIN32 -D_CRT_SECURE_NO_WARNINGS)
    else (WIN32)
        target_compile_options(FreeImage PRIVATE -w)
    endif(WIN32)

endfunction()

init_freeimage()
